server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    username: 'saucekode'
    url: jdbc:postgresql://localhost:5432/user
    password: 'soft234#'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    enabled: true
    url: jdbc:postgresql://localhost:5432/user
    baseline-on-migrate: true

shoplyst:
  app:
    jwtSecret: 'quickfoxranoverthedogandslammedthedoorshut'
    jwtExpirationMs: 86400000

app:
  cors:
    allowedOrigins:

